jenkins:
  securityRealm:
    ldap:
      configurations:
      - managerDN: ${ldapManagerDN}
        managerPasswordSecret: ${sec_globalPassword}
        rootDN: ${ldapRootDN}
        server: ${ldapServer}
        userSearch: ${ldapUserSearch}
  authorizationStrategy: "cloudBeesRoleBasedAccessControl"
  remotingSecurity:
    enabled: true
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
globalCredentialsConfiguration:
  # vaultGlobalConfiguration:
  #   authentications:
  #   - appRoleAuthentication:
  #       id: "cbci-oc"
  #       roleId: "REPLACE_ME"
  #       secretId: "REPLACE_ME"
  #   skipSslVerification: true
  #   url: "${vault_url}"
# credentials:
#   system:
#   cloudbeesHashicorpVault:
#     domainCredentials:
#     - credentials:
#       - vaultUsernamePassword:
#           description: "cbci-oc/secret-a"
#           id: "cbci-oc_secret-a"
#           passwordKey: "password"
#           usernameKey: "username"
#           vaultSecretEngine:
#             genericKV2SecretEngine:
#               authenticationId: "cbci-oc"
#               mountPath: "secret-v2"
#               path: "cbci-oc/secret-a"
#       - vaultSecretText:
#           description: "cbci-oc/secret-b"
#           id: "cbci-oc_secret-b"
#           secretKey: "secret"
#           vaultSecretEngine:
#             genericKV2SecretEngine:
#               authenticationId: "cbci-oc"
#               mountPath: "secret-v2"
#               path: "cbci-oc/secret-b"
